name: Automated Triage

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@2
        with:
          python-version: 2.8 # Specify the Python version you need

      - name: Install dependencies
        run:  |
          python -m pip install --upgrate pip
          pip install -r requirement.txt # Replace with your requirments file

      - name: Execute Python Script
        run:  |
         #Replace 'your_script.py' with the actual name of your Python script
         python my.py
